import React from 'react'
import Script from 'next/script'

const contact = () => {
  return (
    <div>
      <Script>
        {`alert("Contact page me aapka hardik pandya hai")`}
      </Script>
      This is Contact
      </div>
  )
}

export default contactf

export const metadata = {
  title: "This is cott pag",
  description: "Generated by This is contactttt pag",
};