import React from 'react'

const about = () => {
  return (
    <div>This is Abuot</div>
  )
}

export default about

export const metadata = {
  title: "This is About pag",
  description: "Generated by This is About pag",
};