import { Inter } from "next/font/google";
// import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Facebook - ka Admin ",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <>
        <h1>Admin ka Navbar</h1>
        {children} 
    </>
  );
}
